spring.datasource.url=jdbc:mysql://localhost:3306/budget_management
spring.datasource.username=root
spring.datasource.password=Samarth@9022

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090